# This is a basic workflow to help you get started with Actions

name: Daily-Three-Bot

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  workflow_dispatch:
  schedule:
  # 时间为UTC时间,换算为东八区8:30&14:30
    - cron: '30 0,6 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  start:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
          userid: ${{secrets.USERID}}
          password: ${{secrets.PASSWORD}}
          apikey: ${{secrets.APIKEY}}
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setup Go environment
        uses: actions/setup-go@v3.0.0
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges.
          go-version: 1.18
      
      - name: Go Build
        run: |
          go get .
          go build
      
      # Runs a single command using the runners shell
      - name: Invoke Secrets
        run:
          ./Yet-Another-Xidian-Ncov-Report -u $userid -p $password -key $apikey
